### ISSUE TITLE
Cannot find the container image v1.7.0

### ISSUE THREAD

**Issue by jenting** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1000]
Hello, I cannot find the container image v1.7.0 `k8s.gcr.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver:v1.7.0`,  I see the latest GA stable image is v1.4.0 https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#project-status.

Is there any plan to release the missing container images?

**Comment by mattcary** [comment]
Watch for a PR on https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-cloud-provider-gcp/images.yaml, it's a manual process and we have to wait for the cloud builder to do its thing after we create a release in the driver repo. Hopefully we should be able to get to it today.

**Comment by mattcary** [comment]
There is a problem with the windows version of the cloud build, we're looking into it: https://testgrid.k8s.io/provider-gcp-compute-persistent-disk-csi-driver#post-image-k8s-staging-cloud-provider-gcp.

**Comment by mauriciopoppe** [comment]
The issue with the Windows image build was fixed in #986, the latest run of https://testgrid.k8s.io/provider-gcp-compute-persistent-disk-csi-driver#post-image-k8s-staging-cloud-provider-gcp succeeded

**Comment by jenting** [comment]
Thank you all, can't wait to see v1.7.0 available 🚀

**Comment by jenting** [comment]
Okay, looking forward to see v1.7.1 available 🙏

**Comment by jenting** [comment]
Any updates? @mattcary

**Comment by mattcary** [comment]
We're still trying to sort it out. It seems to have built, but there's no 1.7.0 or 1.7.1 tag in the repository.


/assign @amacaskill

**Comment by mattcary** [comment]
v1.7.1 is released! https://github.com/kubernetes/k8s.io/pull/3819

Thank you for your patience. The master & stable overlays will be updated shortly.
