### ISSUE TITLE
Ginkgo v2 bumps

### ISSUE THREAD

**Issue by MushuEE** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1023]
CSI driver uses Ginkgo v1

[Here in go.mod](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/go.mod#L13)
[Here in prow.sh](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/release-tools/prow.sh#L97)

These images use `kubetest2` which is already bumped to ginkgov2 flags causing failures:
```
	 -------------------------------------------------------------------
	|                                                                   |
	|  Ginkgo timed out waiting for all parallel nodes to report back!  |
	|                                                                   |
	 -------------------------------------------------------------------
 e2e timed out. path: ./_rundir/a6f4cd5f-02fa-11ed-9b09-6e9ee80549f1
[1] flag provided but not defined: -ginkgo.flake-attempts
```

**Comment by MushuEE** [comment]
https://github.com/kubernetes/kubernetes/issues/109744

**Comment by MushuEE** [comment]
https://github.com/kubernetes-sigs/kubetest2/pull/200

**Comment by mattcary** [comment]
release-tools/prow.sh is just synced from the kubenetes-csi repo so that will have to be updated generally. I'm not actually sure if that's plumbed through to test/k8s-integration so maybe we can just update the go.mod deps?

**Comment by mattcary** [comment]
Probably what you did in the filestore driver should work equally well here?

I'm not sure where the go.mod dependency is used; it looks like kubetest2 pulls ginkgo itself (kubetest2-tester-ginkgo)? Maybe that was a kubetest v1 thing.

**Comment by mattcary** [comment]
I've started https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1024

**Comment by spiffxp** [comment]
FWIW this was fixed by https://github.com/kubernetes-sigs/kubetest2/pull/206 if you want to un-pin

**Comment by mattcary** [comment]
We'll keep the pin for now so we don't get accidental breakage.

We need a better process for updating the pin though.
