### ISSUE TITLE
No container image of v1.8.0

### ISSUE THREAD

**Issue by jenting** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1056]
There is no container image of v1.8.0, which means I can't pull image from `k8s.gcr.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver:v1.8.0`

**Comment by mattcary** [comment]
After the image is cut, the cloud build pipeline needs to create an image, then it  needs to be promoted from staging, see https://github.com/kubernetes/k8s.io/pull/4294.

It takes a few days for this process to work out.

/close
