### ISSUE TITLE
`registry.k8s.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver:v1.8.1` image does not exist

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1102]
/kind bug

It seems that the v1.8.1 image does not exist or it is not yet promoted in https://github.com/kubernetes/k8s.io/.

```
% docker pull registry.k8s.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver:v1.8.1
Error response from daemon: manifest for registry.k8s.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver:v1.8.1 not found: manifest unknown: Failed to fetch "v1.8.1"
```

There is a release/tag for [v1.8.1](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/releases/tag/v1.8.1).

**Comment by ialidzhikov** [comment]
@mattcary can you help?

**Comment by mattcary** [comment]
Thanks for the reminder, https://github.com/kubernetes/k8s.io/pull/4567 created.

**Comment by mattcary** [comment]
And merged, the image will populate shortly.

/close
