### ISSUE TITLE
`image.yaml` is same for v1.7 and v1.8 release

### ISSUE THREAD

**Issue by roshanirathi** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1107]
`deploy/kubernetes/images/stable-master/image.yaml` has not been updated with the latest images for releases 1.8.x. `README.md` also doesn't have the latest stable image updated.

Please update the files and kindly confirm what are latest image binaries compatible with v1.8.1.

**Comment by mattcary** [comment]
That is correct, we need to vet sidecar version updates before updating the stable relese.

**Comment by roshanirathi** [comment]
I can see that there is a another new release, but the latest stable image is still `v1.7.2`. 
What image version should I use with the latest release?
