### ISSUE TITLE
Documentation - What accessModes are supported by each offering

### ISSUE THREAD

**Issue by DanielYWoo** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1170]
Hi,

I cannot find the document about the accessModes support for pd-standard, pd-balanced and pd-ssd. Does the driver support all access modes? e.g., ReadWriteOncePod.

Thanks

**Comment by DanielYWoo** [comment]
I think we should have this in the readme.

**Comment by neoakris** [comment]
It seems they chose to put it in the official GKE docs instead  
https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#access_modes

I don't see the newly created access mode of ReadWriteOncePod on the list
