### ISSUE TITLE
Create Postsubmit Kubernetes Integration Tests

### ISSUE THREAD

**Issue by davidz627** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#127]
We should have a post submit for the kubernetes integration tests with every supported version skew.
For example:
Driver Master + Kubernetest Master
Driver Master + Kubernetes v1.12
Driver v0.1.0.alpha + Kubernetes v.1.11
etc.

Would be cool if we could link a live dashboard status on the README.md like "green" or "red" for passing/notpassing

**Comment by davidz627** [comment]
Instructions for dashboard status and adding testgrid entries:
`test-infra/testgrid/README.md`

**Comment by msau42** [comment]
For my tracking, here's all the versions I think we should test:

Stable = officially released images
Staging = images built by CI infra
Head = locally built images (by prow)

| Job name | Driver version | Sidecar version | Kubernetes version | Testing purpose
| ------------- | ------------------- | -------------------- | -------------------------- | ------------
| pull-master | head | staging-latest | head | pr changes
| pull-1.12 | head | staging-latest | 1.12 | pr changes
| ci-master | staging-latest | staging-latest | head | latest
| ci-1.12 | staging-latest | staging-latest | 1.12 | latest
| ci-stable-master | stable | stable | head | official releases
| ci-stable-1.12 | stable | stable | 1.12 | official releases
| ci-staging-master | staging-tag | staging-tag | head | release candidate
| ci-staging-1.12 | staging-tag | staging-tag | 1.12 | release candidate


Starting from driver version 1.0, we should also create a job for every official version we cut for regression testing against Kubernetes.

**Comment by msau42** [comment]
cc @verult

**Comment by msau42** [comment]
Also we may want to duplicate all these jobs for GKE

**Comment by jsafrane** [comment]
no, I think it covers all my needs and much more :-)

**Comment by msau42** [comment]
Also, all the jobs should be duplicated for multi-zone/regional clusters so we can test topology and repd

**Comment by saad-ali** [comment]
Excellent test plan. One of the challenges we've had with the 0.4 release of side car containers is discovering issues when we go to cut official release and ingrate with CSI drivers. This should let us get an early signal. Thank you @msau42!

**Comment by BenTheElder** [comment]
/cc
let me know if you need a hand setting these up.

> Would be cool if we could link a live dashboard status on the README.md like "green" or "red" for passing/notpassing

You can get a badge from prow or testgrid for this.
```
<img alt="Build Status" src="https://prow.k8s.io/badge.svg?jobs=ci-kind-build" />
```
=>
<img alt="Build Status" src="https://prow.k8s.io/badge.svg?jobs=ci-kind-build">

```
<img alt="Build Status" src="https://testgrid.k8s.io/q/summary/sig-testing-kind/ci%20build/tests_status" />
```
=>
<img alt="Build Status" src="https://testgrid.k8s.io/q/summary/sig-testing-kind/ci%20build/tests_status" />

**Comment by msau42** [comment]
Thanks @BenTheElder !  I'm actually wondering if we could get someone to help setup an OSS build/push job.  It turns out the CI that we setup for GKE images cannot be accessed publicly.

**Comment by fejta** [comment]
The easiest way for this to work will be to provide a `bazel run //path/to/your/images:push` target [like we do for prow](https://github.com/kubernetes/test-infra/blob/c4e161dcea773321c2a4fcbdea29c50aecab65ad/prow/bump.sh#L83-L84)

**Comment by msau42** [comment]
@saikat-royc has done most of the work getting all the pre-release and post-release jobs and permutations going. Most if it is handled internally. Publicly, we have a few limited jobs testing against stable released versions and csi migration.

Here's the public dashboard: https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver

/close
