### ISSUE TITLE
Race condition between csi-driver and GCP

### ISSUE THREAD

**Issue by dguendisch** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1290]
We frequently run into situations where a pod's volume cannot be attached to some node Y, because on GCP it is still attached to a node X where the pod was previously located. In K8s there are however no traces of the volume being attached to node X, specifically there is no `volumeattachment` resource mapping the volume to node X and node X' `.status.volumesAttached/volumesInUse` has no signs of that volume; this indicates that it (at some point in time) was successfully detached from X.

After a lot of digging (in gcp-csi-driver and GCP audit logs) I found the following race condition to happen presumably because there is no ordering of sequential operations or locking of ongoing operations happening, this is the ordered sequence of events:

- csi-driver attaches disk to node X; gcp-csi-driver times out but GCP tracked the request `gcp-operation-ID: 1`
- csi-driver attaches disk to node X again; this time it succeeds (`gcp-operation-ID: 2`)
- pod gets rescheduled to another node Y about 2 mins later, so the volume must move from node X to node Y
- csi-driver detaches disk from node X and succeeds (`gcp-operation-ID: 3`)
- now `gcp-operation-ID: 1` (resurrected from the dead) finally succeeds; disk is attached to node X again
- csi-driver tries to attach disk to node Y (because of the pod reschedule) and never succeeds

**Comment by mattcary** [comment]
Hmm, arcus lifo queuing is the ultimate problem here. We'd fixed a bunch of these races with the error backoff (I think it was) but it seems there's still a few out there.

I'm not sure what the right fix is TBH. Since the volume is never marked on the old node, the attacher won't know that it needs to be detached.

**Comment by mattcary** [comment]
A fix in arcus (the GCE/PD control plane) is actually in process of rolling out. This fix will enforce fifo of operations and will merge things like op 1 and op 2 in your example. The rollout should be complete in about a month.

The workarounds we've discussed for this at the CSI layer all of various levels of hackery and danger around them, so I think it's best to just wait for the arcus fix.

**Comment by dguendisch** [comment]
Thank you for this follow up! Glad to hear about arcus enforcing fifo soon 👍

**Comment by dguendisch** [comment]
qq: is the above fix meanwhile rolled out?

**Comment by ialidzhikov** [comment]
> qq: is the above fix meanwhile rolled out?

@mattcary @msau42 any news about the above question?

**Comment by ialidzhikov** [comment]
> > qq: is the above fix meanwhile rolled out?
> 
> @mattcary @msau42 any news about the above question?

ping

**Comment by msau42** [comment]
The fix is currently rolling out. Should be complete within the next few weeks.

**Comment by ialidzhikov** [comment]
Thanks @msau42 ! Please let us know in this issue when the fix rollout is complete in this issue. We continue to see the above-described issue in our GCP clusters.

**Comment by jahantech** [comment]
Is there a way for us to track this fix? Thank you. Any issue or commit that we can look forward to?

**Comment by mattcary** [comment]
There's no public tracker for the arcus rollout, unfortunately. There were some problems detected late last year that had to be fixed, and the final rollout is in progress now.

**Comment by adenitiu** [comment]
Any update on the rollout of the fix ?

**Comment by ialidzhikov** [comment]
@msau42 @mattcary can you confirm that the fix rollout in GCP is complete?

**Comment by mattcary** [comment]
Sorry for dropping this. The fix was rolled out by the end of January. Any race conditions seen recently are due to something else and may be worth looking into fixing in this driver.

/close
