### ISSUE TITLE
Recommended beta image, v0.2.0.beta, for v1.12.x support does not exist

### ISSUE THREAD

**Issue by mattkelly** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#137]
The `v0.2.0.beta` image is recommended (actually required) for Kubernetes v1.12.x, but it does not exist:

```
docker pull gcr.io/google-containers/volume-csi/gcp-compute-persistent-disk-csi-driver:v0.2.0.beta
```
```
Error response from daemon: manifest for gcr.io/google-containers/volume-csi/gcp-compute-persistent-disk-csi-driver:v0.2.0.beta not found
```

There is also no corresponding release in GitHub.

References:
- [Official compatibility matrix](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#kubernetes-compatibility)
- [`stable` deployment](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/kubernetes/stable/controller.yaml#L45)

**Comment by davidz627** [comment]
Looks like we might have some delays with pushing the new image due to new processes...
In the meantime, please use the last available tag https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/tree/v0.1.0.alpha

**Comment by mattkelly** [comment]
Thanks for the quick update, @davidz627. My understanding from the README is that `v0.1.0.alpha` is not compatible with Kubernetes v1.12.x (which is what I'm interested in integrating with), so I'll hold off for now. Looking forward to the new image.

**Comment by mattkelly** [comment]
@davidz627 sorry to be an annoyance, but do you happen to have an ETA for the image being pushed?

**Comment by msau42** [comment]
@mattkelly I am hoping to get the image published by end of this week.  In the meantime, you can try using the specs from the 0.1.0 alpha tag, or if this is for dev testing, you can try images from the dev deployment.

**Comment by msau42** [comment]
@mattkelly we pushed official images for v0.2.0, but we may need to make some more breaking changes, so we're keeping v0.2.0 as alpha for now.

/close
