### ISSUE TITLE
Images for v1.11.2 and v1.20.0 are missing 

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1397]
```
$ regctl tag list registry.k8s.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver | grep v1.11
v1.11.0
v1.11.1
```

**Comment by roshanirathi** [comment]
+1

Images for v1.12.0 are same as 1.10.1. They have not been updated.

**Comment by roshanirathi** [comment]
@mattcary @sunnylovestiramisu @msau42 @songjiaxun 
Please give an update as to when can we expect the new images for the new releases?

**Comment by sunnylovestiramisu** [comment]
@roshanirathi There is another release planned for next week, @msau42 will add the images you requested.
