### ISSUE TITLE
Collect driver logs for k8s test

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#140]
We can do something like https://github.com/kubernetes/kubernetes/pull/69986

**Comment by davidz627** [comment]
/remove-lifecycle stale
This would be incredibly helpful for debugging

**Comment by msau42** [comment]
Sample driver logs: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-compute-persistent-disk-csi-driver/554/pull-gcp-compute-persistent-disk-csi-driver-kubernetes-integration/1283548649288110080/artifacts/pd-csi-driver/
