### ISSUE TITLE
Should validate zones during CreateVolume call.

### ISSUE THREAD

**Issue by jingxu97** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#151]
In current controller, when calling create volume, we first check the existing volumes with the name. But it does not validate whether the zones from the existing volumes are matching the required zones or not.

**Comment by davidz627** [comment]
`CreateVolumeResponse` should also contain the zones returned by the cloud provider, not the ones given to the cloud provider

**Comment by davidz627** [comment]
This seems to have been resolved at some point, we get the existing disk based on the "name/zone or name/region" key. 
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/fd8d6416f463f03fd408e996a3c4ad4950480d39/pkg/gce-pd-csi-driver/controller.go#L155

The return value also contains the zones we actually used:
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/fd8d6416f463f03fd408e996a3c4ad4950480d39/pkg/gce-pd-csi-driver/controller.go#L212
