### ISSUE TITLE
Unable to pull the CSI driver image from registry.k8s.io

### ISSUE THREAD

**Issue by abubakarm94** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#1578]
Hi, 

I'm getting the following error message while trying to pull the CSI driver image from `registry.k8s.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver`. Has the image not been pushed?

```
docker pull registry.k8s.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver:v1.13.0
Error response from daemon: manifest for registry.k8s.io/cloud-provider-gcp/gcp-compute-persistent-disk-csi-driver:v1.13.0 not found: manifest unknown: Failed to fetch "v1.13.0"
```

Thanks in advance,
Abubakar

**Comment by kon-angelo** [comment]
Should be solved by https://github.com/kubernetes/k8s.io/pull/6313 when merged
