### ISSUE TITLE
Support for Volume Source (cloning)

### ISSUE THREAD

**Issue by davidz627** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#161]
CSI v1.0 introduced volume source (cloning), the GCE PD driver should implement that

/cc @jingxu97

**Comment by davidz627** [comment]
@jingxu97 should we close this issue since GCE PD does not support clone?

**Comment by jingxu97** [comment]
I think we currently have a KEP open for this. Let me check and update the status for this feature.

**Comment by davidz627** [comment]
/open
still needed

**Comment by davidz627** [comment]
@jingxu97 update with status?

**Comment by davidz627** [comment]
/remove-lifecycle stale
KEP is apparently somewhere

**Comment by msau42** [comment]
/close
for now. I'm not aware of a cloning feature for PD

**Comment by msau42** [comment]
/reopen

This is a thing: https://cloud.google.com/compute/docs/disks/add-persistent-disk#source-disk

/assign @mattcary
