### ISSUE TITLE
[IMPORTANT] Take advantage of `csi_secret` in CSI 1.0

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#180]
CSI 1.0 decorates sensitive fields with `csi_secret`. Let's take advantage of this feature to programmatically ensure no sensitive fields are ever logged by this driver.

**Comment by saad-ali** [comment]
CSI 1.0 decorates senstive fields with `csi_secret`. Let's take advantage of this feature to programmatically ensure no sensitive fields are ever logged by this driver.

**Comment by davidz627** [comment]
Marking this as high priority so that we dont have security issues. GCE PD doesn't actually accept any secrets but if a user mistakenly sends them in, we still don't want to log them
