### ISSUE TITLE
Support PUBLISH_READONLY capability

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#185]
This was introduced in 1.0 and will be enforced by csi-attacher: https://github.com/kubernetes-csi/external-attacher/pull/98

**Comment by davidz627** [comment]
was added here: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/159/files#diff-6ccd9fb670285bf141dea5e99fb3d874R67

are there any other changes necessary?

**Comment by msau42** [comment]
Nope, that should be good, thanks
/close
