### ISSUE TITLE
Set MaxVolumesPerNode on NodeGetInfo call based on Node Type

### ISSUE THREAD

**Issue by davidz627** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#19]
Currently `NodeGetInfoResponse` returns the default of `0` for `MaxVolumesPerNode` so the CO will decide how many volumes can be published on a node.

For GCE we need to return a different number based on node type as the Max Attachable Volumes depends on the number of vCPUs the instance has.

For the actual limits see:
See: https://cloud.google.com/compute/docs/disks/
"persistent disk limits" section

You should be able to GET the instance from the cloud and pull the number of vCPUs from that.
Bonus: We seem to need information from the node object a lot, caching the relevant information somewhere would be nice. Maybe in the `GCENodeServer` object

**Comment by Mockery-Li** [comment]
Hi, I want to take this as my first issue, and I hope to make sure I did not misunderstand the problem.
Is it about modifying `GetMaxVolumesPerNode()` in csi.pb.go (both V0 and V1), to pull the number of vCPUs as the default return value when it knows it's under GCE environment?

**Comment by davidz627** [comment]
Hi @Mockery-Li! Thank you for your interest :)

To implement `MaxVolumesPerNode` you will not have to modify `csi.pb.go`. That is the CSI Specification Protobuf and is generated from the [CSI Specification](https://github.com/container-storage-interface/spec/blob/master/spec.md)

What this issue entails is modifying `NodeGetInfo` in `pkg/gce-pd-csi-driver/node.go` to return a value `MaxVolumesPerNode`.

The max number of nodes can be determined via machine type: see [Persistent Disk Limits section](https://cloud.google.com/compute/docs/disks). You should be able to get the Machine type through the Metadata Service in `pkg/gce-cloud-provider/metadata/metadata.go` (I am not 100% sure about this part).

This should just be a matter of piping the metadata service through to the `Node` service and making the machine type checking call in the `NodeGetInfo` function and casing on the Machine Type.

Hope that is enough information to get you started. Feel free to reach out to me on the Kubernetes Slack (I am `davidz627` there as well) or post questions on this issue if you are wanting guidance. Looking forward to your Pull Request!

**Comment by msau42** [comment]
You can probably also copy a lot of the functionality from [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/gcepd/gce_pd.go#L126)

**Comment by davidz627** [comment]
That's true but I think there are a few differences in the current state (and the driver) from that code.

1. I think the metadata server might be an "easier" source of the machine type information as we wont need the GCE credentials: see [machine-type](https://cloud.google.com/compute/docs/storing-retrieving-metadata)
2. I think GCE has changed their supported attach limits for disks since that code was written (?). From what I see:
"For most instances with custom machine types or predefined machine types, you can attach up to 128 persistent disks.
Instances with shared-core machine types are limited to a maximum of 16 persistent disks."

**Comment by Mockery-Li** [comment]
Thank you. I'm trying both methods.
To adapt the function @msau42 mentioned, we may need to get CloudProvider inside NodeService? It seems a little bit strange to access that directly using `cloud := ns.Driver.cs.CloudProvider`, but this is the only way I've come up with.
As for using machine-type like @davidz627 said, I have not figured out how to use the metadata (projectID/zone/name). The detailed question has been sent through Slack, need some further help, thanks.
