### ISSUE TITLE
XFS test is passing when it shouldn't be

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#192]
XFS is not supported on COS.

https://testgrid.k8s.io/sig-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Stable

**Comment by davidz627** [comment]
potentially due to driver not respecting filesystem option passed in (bug needs to be fixed)

The test should also be modified so that it is actually verifying what kind of filesystem is being formatted to catch these types of errors.
https://github.com/kubernetes/kubernetes/issues/71528

**Comment by davidz627** [comment]
Resolved here: https://github.com/kubernetes/kubernetes/pull/70823
e2e tests now check fsType and xfs tests disabled for gce pd
