### ISSUE TITLE
Driver cluster deployment should have cluster-driver-registrar

### ISSUE THREAD

**Issue by davidz627** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#205]
we should deploy with cluster-driver-registrar which creates the CSIDriverInfo object IIUC.

/cc @msau42

**Comment by msau42** [comment]
DriverInfo is needed for two features, which PD driver doesn't use:
- skip attach
- pod info on mount

**Comment by davidz627** [comment]
It's possible `DriverInfo` will be required for some other feature in future, is it better to have the driver deploy with it anyway?

**Comment by msau42** [comment]
I think until we need it, we shouldn't add it.  It will just take up more resources then necessary.
