### ISSUE TITLE
external-snapshotter deployment issues

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#212]
Only the dev deployment script deploys an external-snapshotter. 

https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/191be851fce1ff624208be29a253f2961c861339/deploy/kubernetes/overlays/dev/controller_images.yaml#L13-L15

1) Shouldn't the stable deployment script also deploy the external snapshotter (at least as a flag controlled option)?

2) The external-snapshotter in dev is out of date and results in the controller crash looping:

```
  csi-snapshotter:
    Container ID:  docker://2c24cd5a64a38d1bfebf898cf8779070184e541c90c3ce7204d313aba893c863
    Image:         quay.io/k8scsi/csi-snapshotter:v0.4.0
    Image ID:      docker-pullable://quay.io/k8scsi/csi-snapshotter@sha256:e2cc9f3e61d53e4fd35b96c103bcea48ca41ef3b38662f94e9da749f359ba130
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --csi-address=$(ADDRESS)
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 19 Dec 2018 22:03:11 -0800
      Finished:     Wed, 19 Dec 2018 22:03:11 -0800
    Ready:          False
    Restart Count:  5
```

It is crash looping because the external-snapshotter version is wrong:
```
$ kubectl logs csi-gce-pd-controller-0 -c csi-snapshotter
I1220 06:05:52.112139       1 main.go:76] Version: v0.4.0-4-ge6d7b9ac
I1220 06:05:52.144724       1 connection.go:83] Connecting to /csi/csi.sock
I1220 06:05:52.144908       1 connection.go:111] Still trying, connection is CONNECTING
I1220 06:05:52.145223       1 connection.go:108] Connected
I1220 06:05:52.145248       1 connection.go:259] GRPC call: /csi.v0.Identity/GetPluginInfo
I1220 06:05:52.145672       1 connection.go:261] GRPC response: 
I1220 06:05:52.145721       1 connection.go:262] GRPC error: rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
E1220 06:05:52.145746       1 main.go:131] rpc error: code = Unimplemented desc = unknown service csi.v0.Identity
```

The external-snapshotter version should be updated to point to a CSI 1.x version.

3) `external-snapshotter` only exists on `quay` not on `gcr.io/gke-release`. We should have external-snapshotter deployed on `gcr.io/gke-release`.

CC @jingxu97 @davidz627

**Comment by msau42** [comment]
1. Let's create a new "alpha" config to deploy the snapshotter container.
2. This should be updated to use snapshotter v1.0.x
3. We need to create new internal flows to build snapshotter. Will sync up with jing offline

**Comment by davidz627** [comment]
resolved with multiple PRs.

Snapshotter has been updated, and there is now an alpha config with the external snapshotter
/close
