### ISSUE TITLE
usage of same volume by multiple pods on same node

### ISSUE THREAD

**Issue by pohly** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#219]
Although not covered by the CSI spec (see https://github.com/container-storage-interface/spec/pull/150 and https://github.com/container-storage-interface/spec/issues/178), according to @msau42 the gcepd driver should support running two pods on the same node, using the same volume.

However, during testing of https://github.com/kubernetes/kubernetes/pull/72002 the gcepd driver didn't pass the new "concurrent pods" tests. Therefore the test is currently not enabled for that driver.

**Comment by msau42** [comment]
It was an issue with the test case that has been fixed.
/close
