### ISSUE TITLE
Adding volume operation metrics

### ISSUE THREAD

**Issue by verult** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#276]
Does the CSI driver need Prometheus metrics?

Possible metrics:
* GCP cloud provider calls
  * latency and error rates of GCE PD calls. We can compare the latency against the corresponding k8s volume operation latency to discover inefficiencies.
  * latency and error rates AltTokenSource oauth calls

**Comment by saad-ali** [comment]
CSI Metrics were added to the side car containers in the following PRs:
* https://github.com/kubernetes-csi/external-provisioner/pull/388
* https://github.com/kubernetes-csi/external-attacher/pull/201
* https://github.com/kubernetes-csi/external-snapshotter/pull/227
* https://github.com/kubernetes-csi/external-resizer/pull/67

These PRs are available in the following sidecar releases:
* external-provisioner v1.5.0+
* external-attacher v2.1.0+
* external-snapshotter v2.0.0+
* external-resizer v0.4.0+

Distributors of this driver who want to enable the CSI Metrics should 1) ensure they deploy the correct version of the side car containers (see above), and 2) ensure the `metrics-address` and `metrics-path` flags are set for each of the sidecar containers specified above.
