### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by davidz627** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#30]
* Add Known Issues
* Add Project Status
* Add Plugin Features (supported parameters)
* Add Future Features
* Add User Guide
  * Improve setup scripts to work every time, with reasonable error messages when variables not defined
* Add Kubernetes Development
* Add Dependency Management Information

**Comment by msau42** [comment]
I think it would also be better to restructure the front page README to focus on the user guide, more than development (there should will be more users than devs visiting the page)
