### ISSUE TITLE
Old release branch tests should run new "External PD" style tests when running with k8s HEAD

### ISSUE THREAD

**Issue by davidz627** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#300]
https://testgrid.k8s.io/sig-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Release%200.4

https://testgrid.k8s.io/sig-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Release%200.3

These configs are currently skipping all tests since they are trying to run on Kubernetes HEAD which removed the "CSI.*gcePD-external" tests in favor of the "External.Storage" style tests.
However there should be a way to configure that if we're running on an older version of k8s like <= 1.13 we use the old "CSI.*gcePD-external" test focus...

**Comment by msau42** [comment]
Test against older versions of Kubernetes instead of HEAD?

**Comment by davidz627** [comment]
don't we want to validate that older versions of the driver still work on newer versions of k8s too?

**Comment by davidz627** [comment]
/close
pruned the old release branch tests. too old and expensive to change with very little upside. We already have tested versions of the driver that support all versions `1.13+`
