### ISSUE TITLE
Add test configs on Ubuntu

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#306]
So we can test xfs

/kind test

**Comment by davidz627** [comment]
I was just in the middle of creating this issue when I found this. Definitely much needed. Should be an easy test config change (change the image family)

**Comment by davidz627** [comment]
/remove-lifecycle stale
xref: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/305

**Comment by msau42** [comment]
/reopen
The ability to test on ubuntu was added, but we don't have an actual config yet.

**Comment by davidz627** [comment]
On my list of things to do this week - just configured the description incorrectly

**Comment by davidz627** [comment]
Test configs added with GKE internally - still have some issues but close to resolution.
