### ISSUE TITLE
Driver doesn't mount with mount options

### ISSUE THREAD

**Issue by davidz627** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#343]
Repro by setting
```
MountOption: debug
```
on the storage class. Then run the demo pod.
Exec into demo pod and check "mount"  you will find that the mount does not have the debug option set

**Comment by msau42** [comment]
also maybe related: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/263
