### ISSUE TITLE
Pre-stop hook to delete registration socket isn't working

### ISSUE THREAD

**Issue by verult** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#365]
Node-driver-registrar moved to distroless, so shelling no longer works. Alternative solution is being discussed at the node-driver-registrar level here: https://github.com/kubernetes-csi/node-driver-registrar/issues/21#issuecomment-517519504

**Comment by davidz627** [comment]
will be fixed in node driver registrar by reconciling the socket and also deleting it on sigterm

**Comment by verult** [comment]
Issue tracking socket reconciliation: 
https://github.com/kubernetes-csi/node-driver-registrar/issues/57

**Comment by jsafrane** [comment]
I'm removing preStop hook from csi-driver-hostpath in https://github.com/kubernetes-csi/csi-driver-host-path/pull/176. It can't work and nobody is adding shell to node-driver-registrar. It would be nice if it was removed from GCE PD manifests too, so kubernetes tests logs are cleaner.

Effort to add signal handling to node-driver-registrar is IMO orthogonal.

**Comment by saad-ali** [comment]
preStop hook was removed in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/520
Whenever https://github.com/kubernetes-csi/node-driver-registrar/issues/21 or https://github.com/kubernetes-csi/node-driver-registrar/issues/57 are tracking the new fix.

/close
