### ISSUE TITLE
Prow spyglass viewer isn't highlighting relevant errors

### ISSUE THREAD

**Issue by verult** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#369]
In [this instance](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-compute-persistent-disk-csi-driver/364/pull-gcp-compute-persistent-disk-csi-driver-kubernetes-integration/1157432232361594881/) of the driver integration test, there isn't any useful error highlighting to help quickly identify where the test failure came from. Also as a result, almost the entire viewer is collapsed by default, instead of exposing the highlighted lines and collapsing everything else.

Per https://github.com/kubernetes/test-infra/pull/13060 it's now possible to configure the regex for highlighting. Would this help?

**Comment by msau42** [comment]
also related is https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/188
