### ISSUE TITLE
Improve Deployment Scripts

### ISSUE THREAD

**Issue by davidz627** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#37]
- [x] Make GCP service account token file user configuratable 
- [x] Figure out actual minimal permissions set required for GCP service account
- [ ] Make namespace configurable

**Comment by davidz627** [comment]
Ideally the user can run 1 script for an End to End deployment, that checks whether things (service account, role bindings, json keys) already exist, and if not, creates them, then is able to deploy the driver. And maybe even clean up the key from the machine afterwards.

**Comment by msau42** [comment]
Sure sounds reasonable

**Comment by davidz627** [comment]
GCP Service Account token file directory configurable: #81 
Minimal permissions: #73 

Still todo:
* Make namespace configurable

**Comment by saad-ali** [comment]
Should the default namespace be default? Or would it be better to have a GCE PD specific namespace?

**Comment by msau42** [comment]
Better to have a special namespace just for the driver

**Comment by davidz627** [comment]
namespace shouldn't be configurable, actually will just be set directly
