### ISSUE TITLE
NodeExpand may resize fs for block volume

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#372]
Looking back at `resizer.Resize` implementation, it checks the format on the disk before attempting a resize.  The problem is, the presence of a filesystem doesn't mean that the PVC is a Filesystem type.  A user could mount the volume as Block and manage an ext4/xfs filesystem themselves.

I think fixing this may require adding VolumeCapabilities to the Controller/NodeExpandVolumeRequest

/kind bug
/assign @davidz627 
cc @gnufied

**Comment by davidz627** [comment]
Just to confirm, the intended behavior is:
If the `VolumeCapability` is `Block` and the user manages a fs by themselves, we should **NOT** resize their fs
?

**Comment by msau42** [comment]
correct

**Comment by gnufied** [comment]
okay, I have file a bug against CSI for adding the capability - https://github.com/container-storage-interface/spec/issues/380

**Comment by gnufied** [comment]
Actually I am wondering if we can solve majority of this problem, without making a change in CSI specs. See when volume is of type raw-block the `volumePath` that you will get with `NodeExpandVolume` will be a device-path not a mounted file system path. So we can use that information and not perform any file system level expansion when `NodeExpandVolume` is called on raw block devices.

I think it may still be worth adding capability to `NodeExpandVolume` and `ControllerExpandVolume` call but - it will fall under "nice" to have territory and a driver can use this optional information to skip a operation entirely.

**Comment by davidz627** [comment]
VolumeCapability was added so this should be easy to skip now

**Comment by verult** [comment]
VolumeCapabilities are now passed into resize call as part of external-resizer v0.5.0.

**Comment by shay-berman** [comment]
What is the status of this ticket please?
Looks like it blocking the GA of the GKE CSI driver.

**Comment by shay-berman** [comment]
Great to see that [GA Driver](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/projects/6) project is all done.
May I ask when the GKE [documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/gce-pd-csi-driver) will be update about using the GA driver vs the Beta version?

**Comment by msau42** [comment]
Once it's completely rolled out in GKE, which will start in rapid channel and eventually reach the stable channel, we will update the GKE documentation. It will take a few weeks to reach stable as it needs to first soak in rapid, then regular channels.

**Comment by gnufied** [comment]
Did we wanted to expand this functionality and return `false` from `ControllerExpandVolume` , if it is called for block volume types? That would eliminate need for calling NodeExpandVolume altogether.

**Comment by shay-berman** [comment]
@msau42 I am using GKE CSI beta today, just want to make sure. Is there going to be upgrade pass from PVC that were created via the GKE CSI beta to the GAed CSI version?

Do I need to take any action in order to get the CSI GAed version while running on GKE?

Thanks

**Comment by msau42** [comment]
@shay-berman no changes needed. The GA driver is compatible with the beta. The only action you may need to take is to upgrade your GKE cluster to get the GA driver if you are not on a release channel.
