### ISSUE TITLE
udevadm may be never triggered right now

### ISSUE THREAD

**Issue by ZeroMagic** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#376]
In the function `VerifyDevicePath`(https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/pkg/mount-manager/device-utils.go#L89), the value of `sdBefore` is the same with `sdAfter`. 

Then the function `udevadmChangeToDrive` will never be called. It seems like the code doesn't actually do anything. 

/ping @davidz627

**Comment by davidz627** [comment]
This is true, the code as-is doesn't do anything :) thanks for the find.
The intent for udevadm triggers is to "workaround" two known errors.
- The disk has attached and shows up as `/dev/sdx` but does not get symlinked to `/dev/disk/by-id/` which we rely on for finding the correct disk
- A disk was detached (at `/dev/sdy`), a different one has attached also at `/dev/sdy` and the `/dev/disk/by-id/` symlinks are stale (?)
  - @msau42 I feel like I didn't write this second one properly could you confirm/edit

The actual solution to this would be as follows:
- Check that the disk at `/dev/disk/by-id/` has a SCSI Serial that matches the `diskName` that we expect
  - If not, run a udev fix on it
- If the `/dev/disk/by-id` does not exist, we then have to trigger the udev fix on the `/dev/sdx` of the missing disk
  - Finding this disk poses an issue, the clumsy method we can think of right now is to take the set of all disks in `/dev/disk/by-id` and diff them with the set of `/dev/sdx` and run the udev fix on all the diffs until we get the symlink that we want
    - The issue with this method is that we will trigger udev on disks that may be attached that are not `PD` repeatedly (this is not ideal but may not be a terrible problem).

@ZeroMagic please let me know and assign yourself if you are interested in working on this fix. If not, considering this is a known issue that occurs infrequently we do not consider this high priority and will fix it sometime before GA.

**Comment by ZeroMagic** [comment]
@davidz627 Oh, I'm afraid not. I have no time to fix it recently.
