### ISSUE TITLE
Run E2E Tests With Containerized Driver

### ISSUE THREAD

**Issue by davidz627** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#39]
Currently E2E tests just copy the binary onto an instance to run the tests. They should run the tests with the containerized version of the driver because that is what the end user will likely be consuming, it will also detect errors in the containerization process.

**Comment by msau42** [comment]
Do we need this now that we have kubernetes e2e tests?

**Comment by davidz627** [comment]
not necessary anymore
