### ISSUE TITLE
[Feature Request] Possibility to overwrite volume limits

### ISSUE THREAD

**Issue by bertinatto** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#422]
As part of the work for graduating volume limits to GA in kubernetes v1.17, I'd like to run our e2e tests against a real CSI driver, more specifically, the PD driver.

However, the current limit (127 volumes) has been challenging to work with, since it generates many requests. The test gets constantly rate-limited and kubernetes backoff kicks in, so the run time slows down substantially.

That being said, I'd be interesting to have a way to set the volume limit for the driver. It could be a CLI parameter or an env variable, for example.

**Comment by msau42** [comment]
It could also indicate that we can't realistically support the limit we claim to support.
