### ISSUE TITLE
It's "overridden"?

### ISSUE THREAD

**Issue by zhucan** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#426]
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/fa208e7e147b518795c6147d751bcb38453c1152/pkg/mount-manager/fake-safe-mounter.go#L67

@davidz627

**Comment by davidz627** [comment]
@zhucan feel free to submit a PR to fix. IF you find other spelling errors please collate them into one PR

**Comment by zhucan** [comment]
@davidz627 ok, I will take a look
