### ISSUE TITLE
Failed getting Project and Zone: Get http://169.254.169.254/computeMetadata/v1/instance/zone: dial tcp 169.254.169.254:80: connect: connection refused

### ISSUE THREAD

**Issue by ravithati-cse** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#430]
Hi,

I am trying to setup CSI with OpenShift4.2 on GCP. My cluster shows healthy & I have deployed gcp-compute-persistent-disk-csi-driver as described in user docs of this project.

The controller "csi-gce-pd-controller-0" is faling with below errors.  Does the csi deployment in openshift need something more? i see its connection refused unlike "sa" account insufficient privileges on gcp.

I1108 19:35:03.519891       1 main.go:60] Driver vendor version v0.6.0-gke.0
I1108 19:35:03.519946       1 gce.go:81] Using GCE provider config <nil>
I1108 19:35:03.520094       1 gce.go:133] GOOGLE_APPLICATION_CREDENTIALS env var set /etc/cloud-sa/cloud-sa.json
I1108 19:35:03.520102       1 gce.go:137] Using DefaultTokenSource &oauth2.reuseTokenSource{new:jwt.jwtSource{ctx:(*context.emptyCtx)(0xc000092020), conf:(*jwt.Config)(0xc00027c140)}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}

Failed getting Project and Zone: Get http://169.254.169.254/computeMetadata/v1/instance/zone: dial tcp 169.254.169.254:80: connect: connection refused

Appreciate any help
Ravi

**Comment by jsafrane** [comment]
OpenShift 4.x does not support accessing link-local IP addresses from withing a container (`169.254.169.254`). Please use `hostNetwork: true` for the driver pods and/or contact your OpenShift support.

**Comment by ravithati-cse** [comment]
Thank you @jsafrane. It helped my understanding & being a Lab setup I could resolve it by deploying as privileged containers & hostNetwork: true.  I will work with OpenShift support to run as restricted containers.
