### ISSUE TITLE
PKGDIR in setup_project.sh point to sigs.k8s.io instead of github.com/kubernetes-sigs

### ISSUE THREAD

**Issue by stiller-leser** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#440]
Hi,

not sure if I tried to clone the driver correctly to my system. I tried to run `go get -v github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver` in order to position it in the `GOPATH` of my cloudshell on GCP.

In this case the `PKGDIR` in `setup_project.sh` points to the wrong location (see [this commit](https://github.com/stiller-leser/gcp-compute-persistent-disk-csi-driver/commit/98d4f7ce157fd30a95e2a19d0159e5f7b3825e3d))

Is this a bug or a user issue? If it is an user issue, could you kindly update [the installation documentation](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/docs/kubernetes/user-guides/driver-install.md) on how to rightly clone the driver to a local system? If not, I'd be happy to contribute my commit as PR.

Best regards,
stiller-leser

**Comment by davidz627** [comment]
Hi @stiller-leser , this is a documentation issue. The driver should be cloned to the `sigs.k8s.io` path which is convention among most `kubernetes` projects. Would you be willing to update the installation instructions with that step?

**Comment by davidz627** [comment]
Thanks for this fix @stiller-leser! Appreciate it :)
