### ISSUE TITLE
failed to insert zonal disk: unkown Insert disk error: googleapi: Error 503: Internal error. Please try again or contact Google Support. (Code: '0'), backendError

### ISSUE THREAD

**Issue by JohnRobinv** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#446]
I'm trying to set up CMEK in my cluster as per the details mentioned here:
[dynamically_provision_an_encrypted](https://cloud.google.com/kubernetes-engine/docs/how-to/dynamic-provisioning-cmek#dynamically_provision_an_encrypted)

I have deployed the Compute Engine Persistent Disk CSI Driver to my cluster as per the steps mentioned in:
[driver install](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/docs/kubernetes/user-guides/driver-install.md)

PFA the gcp-compute-persistent-disk-csi-driver-specs-generated.yaml file.

[gcp-compute-persistent-disk-csi-driver-specs-generated.txt](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/files/3770206/gcp-compute-persistent-disk-csi-driver-specs-generated.txt)

I tried to change the apiVersion from scheduling.k8s.io/v1 to scheduling.k8s.io/v1beta1 and re-ran the deploy-driver.sh script. This time, the script successfully ran. Both priorityclass.scheduling.k8s.io/csi-gce-pd-controller and priorityclass.scheduling.k8s.io/csi-gce-pd-node were created.

I have then created the key/key ring and have created the below storage class:
```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: csi-gce-pd
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
  disk-encryption-kms-key: "projects/xx/locations/us-central1/keyRings/xx/cryptoKeys/xx
```

Below is the YAML for the PVC:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: podpvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-gce-pd
  resources:
    requests:
      storage: 6Giroot
```

However, when i apply the PVC YAML, it fails with the below error and PVC status will be at pending:
```
# kubectl describe pvc podpvc
Name:          podpvc
Namespace:     default
StorageClass:  csi-gce-pd
Status:        Pending
Volume:
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"podpvc","namespace":"default"},"spec":{"accessModes...
               volume.beta.kubernetes.io/storage-provisioner: pd.csi.storage.gke.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason                Age               From                                                                                                          Message
  ----     ------                ----              ----                                                                                                          -------
  Normal   Provisioning          7s (x4 over 21s)  pd.csi.storage.gke.io_gke-simple-gke-cluster-default-pool-496f2fea-v110_3be27592-a12e-41f3-a22d-c3591237c894  External provisioner is provisioning volume for claim "default/podpvc"
  Warning  ProvisioningFailed    6s (x4 over 18s)  pd.csi.storage.gke.io_gke-simple-gke-cluster-default-pool-496f2fea-v110_3be27592-a12e-41f3-a22d-c3591237c894  failed to provision volume with StorageClass "csi-gce-pd": rpc error: code = Internal desc = CreateVolume failed to create single zonal disk "pvc-f1fe929e-2adc-11ea-8792-4201ac101004": failed to insert zonal disk: unkown Insert disk error: googleapi: Error 503: Internal error. Please try again or contact Google Support. (Code: '0'), backendError
  Normal   ExternalProvisioning  5s (x4 over 21s)  persistentvolume-controller                                                                                   waiting for a volume to be created, either by external provisioner "pd.csi.storage.gke.io" or manually created by system administrator
```

Can please someone know why is this happening and what can be done to resolve this.

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.7-gke.23", GitCommit:"81c87c699557fed991e292cd328b2129c2f242a2", GitTreeState:"clean", BuildDate:"2019-11-07T19:23:23Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by msau42** [comment]
Hi @JohnRobinv, can you file a support issue to triage further?

**Comment by JohnRobinv** [comment]
@msau42 , could you suggest how to do that?

**Comment by msau42** [comment]
Here's the GCP support page with instructions on how to file a support ticket:
https://cloud.google.com/support/docs/

The reason why I suggest filing a support ticket is because the error seems like a GCP backend error, not a problem with the CSI driver, and we may need to look at more detailed GCP logs to figure out the problem. cc @davidz627 to also double check

**Comment by davidz627** [comment]
without full logs this is hard to debug further. I agree with Michelle that based on the error message this seems like a GCP backend error. However, I would expect that this error is transient and should resolve itself eventually. The system should retry creation of the disk until success as long as your API objects continue to exist in their desired configuration. Are you still encountering this error or have disks been created successfully afterwards?

Whether you are still encountering this error or not I would still recommend filing a support ticket so that we can get to the bottom of this and make sure it doesn't happen again.

**Comment by JohnRobinv** [comment]
Thank you. @msau42 
At last I found the root cause is the key. The key I used is not available. After creating a new one.
The PVC provisioning normally.

**Comment by davidz627** [comment]
@JohnRobinv could you clarify what you mean by "key used not available"? Was the key revoked, service account no permissions, key didn't exist at all, or other? The error message wasn't very clear and I want to make sure we get a good error message printed when this happens in the future!
