### ISSUE TITLE
Update deployments to include new snapshot controller (for v1beta1 APIs), start running tests, and update docs

### ISSUE THREAD

**Issue by davidz627** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#457]
Looks like some new snapshot APIs went Beta in k8s `1.17`. The corresponding `external-snapshotter` is also available and tested with the PD Driver. However, the stable deployment in this repo still does not contain the snapshotter, tests are not run by default, and the documentation for snapshotting may be out of date.

**Comment by msau42** [comment]
/reopen
One last item is to enable the e2e tests.

**Comment by msau42** [comment]
/reopen
To close when we add it to stable overlay

**Comment by saikat-royc** [comment]
a new driver release and documentation changes are still pending for this
