### ISSUE TITLE
CI Tests take 1+ hour to build Kubernetes causing occasional timeouts

### ISSUE THREAD

**Issue by davidz627** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#464]
Tests only take about 4 minutes to run, building and bringing the driver up only about 10 minutes max.

Kubernetes build takes 1+ hour. We should figure out how to either speed this up or avoid building Kubernetes all together.

/cc @msau42

**Comment by davidz627** [comment]
For example see: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-gcp-compute-persistent-disk-csi-driver-latest-k8s-master-integration/1224771344382562304

We hit the 1.5 hour timeout. Kubernetes build starts at `19:17:54.728` and ends at `20:21:34.589`

**Comment by davidz627** [comment]
ah the yaml definitions dont have the container size requests that we have in GKE infra that give it enough resources to build kubernetes properly..

**Comment by msau42** [comment]
If we're not testing against K8s master, then I'm not sure why we need to build K8s. I believe we were building to get the e2e.test binary, but even then, I don't think we need to do an entire "make quick-release". We could potentially just do "make WHAT=test/e2e/e2e.test"
