### ISSUE TITLE
Unit tests for Node

### ISSUE THREAD

**Issue by davidz627** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#48]

**Comment by Mockery-Li** [comment]
Hi, I have added unit test for GetNodeInfo in issue[#19](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/19), and hope to complete other unit tests for Node.
Is there any sample for testing the mounter?

**Comment by davidz627** [comment]
@Mockery-Li you may be able to find some examples in the existing k8s code: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/gcepd/gce_pd_test.go#L129
^ I'm not really sure if this is what you're looking for but it might be a good starting point

**Comment by msau42** [comment]
For mounter, we usually use the FakeMounter for testing.

**Comment by Mockery-Li** [comment]
Thanks, that's what I need

**Comment by davidz627** [comment]
Closed by #248
