### ISSUE TITLE
Volume restored from snapshot is not ready for use after provisioning

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#482]
E2E flakes saw this error during attach:
```
I0303 02:40:32.854820       1 csi_handler.go:222] Error processing "csi-1683f88fb840d9231ef604066b4ad499db02dd397e96aab70497b0331f73af8e": failed to attach: rpc error: code = Internal desc = unknown Attach error: failed cloud service attach disk call: googleapi: Error 400: The resource 'projects/k8s-gce-serial-1-5/zones/us-west1-b/disks/pvc-25bf62e1-6739-4e79-87a1-3b575faa4daf' is not ready, resourceNotReady
```
Ref: https://github.com/kubernetes/kubernetes/issues/88762#issuecomment-594484135

**Comment by msau42** [comment]
/kind failing-test

cc @yosmat

**Comment by jsafrane** [comment]
It happened during attach of a volume restored from a **snapshot**. `CreateVolume()` returned something that was not attachable for ~4 minutes.

**Comment by msau42** [comment]
cc @yoesmat @yuxiangqian

**Comment by saikat-royc** [comment]
This issue is also tracked in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/526. Will be fixed by PR: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/527. @msau42  we can close this issue as duplicate.
