### ISSUE TITLE
Unable to deploy driver - Failed getting project and zone

### ISSUE THREAD

**Issue by prashantokochavara** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#490]
I've double checked all credentials, but not sure why I keep hitting this issue for any version I deploy - stable or alpha.
![2020-04-17_12-33-44](https://user-images.githubusercontent.com/62115318/79592301-ce76b000-80a7-11ea-902a-921eab7d6d38.png)

Any idea what could be going wrong here?

**Comment by msau42** [comment]
Which version of the driver are you using?

Also, the error message is cut off, could you paste the entire "Failed to get cloud provider" error?

**Comment by msau42** [comment]
I see you are using v0.7.0.

**Comment by prashantokochavara** [comment]
correct - installing the alpha version for snapshot feature support.
Happens with stable, dev, alpha all versions though.

Full output..

I0417 16:33:29.986931       1 main.go:67] Driver vendor version v0.7.0-gke.0
I0417 16:33:29.987006       1 gce.go:80] Using GCE provider config <nil>
I0417 16:33:29.987166       1 gce.go:125] GOOGLE_APPLICATION_CREDENTIALS env var set /etc/cloud-sa/cloud-sa.json
I0417 16:33:29.987176       1 gce.go:129] Using DefaultTokenSource &oauth2.reuseTokenSource{new:jwt.jwtSource{ctx:(*context.cancelCtx)(0xc000296300), conf:(*jwt.Config)(0xc000118780)}, mu:sync.Mutex{state:0, sema:0x0}, t:(*oauth2.Token)(nil)}
F0417 16:33:31.212427       1 main.go:83] Failed to get cloud provider: Failed getting Project and Zone: Get http://169.254.169.254/computeMetadata/v1/instance/zone: dial tcp 169.254.169.254:80: connect: connection refused

**Comment by msau42** [comment]
Do you have `hostNetwork: true` set in the DaemonSet spec?

**Comment by prashantokochavara** [comment]
Nope, I do not. Do I need to add that in the spec somewhere?

**Comment by msau42** [comment]
Yes see https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/a0c8fa2bf78b8e5b52445a67ab782db1a53b75d3/deploy/kubernetes/base/node.yaml#L19

**Comment by prashantokochavara** [comment]
I tried that and still facing the same issue. 
This is an OpenShift environment that I am working with - 4.3 with 1.16 K8. Any supportability issues?

**Comment by msau42** [comment]
@gnufied @jsafrane are you aware of any configuration that needs to be done in openshift to access the GCP metadata server?

**Comment by jsafrane** [comment]
Not sure what's  GCP metadata server... Is it the link-local address to get VM metadata? The DaemonSet pods must use `hostNetwork: true`.

OpenShift does not allow random pods to get to VM metadata, we used to put some sensitive material (don't remember exactly, some certificates?).

**Comment by jsafrane** [comment]
There is nothing else OpenShift specific...

**Comment by msau42** [comment]
Yes I mean link local address to get vm metadata: 169.254.169.254:80: connect: connection refused

**Comment by prashantokochavara** [comment]
@msau42 have we been able to confirm that non-OCP environments are not having this issue?

**Comment by msau42** [comment]
Yes, we have CI running successfully in kubetest GCP environment:
https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Latest

@gnufied @jsafrane are you able to run the pd driver in your ocp environment?

**Comment by jsafrane** [comment]
Yes, I am able to run e2e tests with manifests from https://github.com/kubernetes/kubernetes/tree/master/test/e2e/testing-manifests/storage-csi/gce-pd on GCP.

**Comment by prashantokochavara** [comment]
I'm reading another issue but from an AWS project with similar issues being faced..
https://github.com/aws/aws-node-termination-handler/issues/21

Also, I am hitting similar metadata issues when using EC2 with OCP and EBS CSI Driver.
Is there a common codepath between the two CSI drivers by any chance?

**Comment by prashantokochavara** [comment]
@msau42 
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/474#issuecomment-619115093
Could the GCP Driver be hitting the same thing?

**Comment by msau42** [comment]
Are you trying to run the controller on a node that doesn't have access to the metadata service?

**Comment by msau42** [comment]
There is no common code path between the two drivers, but the ideas are similar. They both require access to the metadata service in order to get project/zone information of the cluster they're running in.

There was work being done in both drivers to remove this requirement and allow controllers to be run outside of the Kubernetes cluster. But it requires additional arguments to be passed into the driver, and is not the normal case.
