### ISSUE TITLE
Driver integration test should support option to deploy GKE managed PD CSI driver

### ISSUE THREAD

**Issue by saikat-royc** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#511]
In https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/test/k8s-integration/main.go, an option should be provided to deploy a GKE Managed driver, so that kubernetes e2e test suites can be run for this managed driver.

**Comment by msau42** [comment]
cc @verult
