### ISSUE TITLE
CSI Migration tests failing

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#513]
https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver#Migration%20Kubernetes%20Master%20Driver%20Latest

/kind failing-test

**Comment by verult** [comment]
The failure is caused by https://github.com/kubernetes-csi/external-attacher/issues/217, which is fixed in external attacher 2.2.0. Tests passed against staging RC overlay.

Since staging tests have been green, the fix is to promote staging images to dev.
