### ISSUE TITLE
Add support for ephemeral volumes

### ISSUE THREAD

**Issue by eyalzek** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#519]
CSI ephemeral volumes are in beta starting kubernetes 1.16. I'm not sure what it would entail to add support to this feature, but it would definitely be nice to have.

https://kubernetes.io/docs/concepts/storage/volumes/#csi-ephemeral-volumes

**Comment by msau42** [comment]
/kind feature
There is an alternative ephemeral volume feature being proposed for 1.19 that will make it easier for general-purpose storage drivers like this one to support. https://github.com/kubernetes/enhancements/issues/1698

**Comment by eyalzek** [comment]
> /kind feature
> There is an alternative ephemeral volume feature being proposed for 1.19 that will make it easier for general-purpose storage drivers like this one to support. [kubernetes/enhancements#1698](https://github.com/kubernetes/enhancements/issues/1698)

That's good to know, thanks for the link!

**Comment by mattcary** [comment]
/close

This issue will be revisited when the various ephemeral proposals sort out.
