### ISSUE TITLE
Change deployment scripts to use kubectl Kustomize integration

### ISSUE THREAD

**Issue by verult** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#522]
Kustomize is now integrated into kubectl. It would be nice to simplify our deployment scripts to use kubectl apply instead.

@msau42

**Comment by mattcary** [comment]
So we do a kustomize edit set image in the driver deploy, which I don't think can be done with kubectl -k. So we need kustomize around anyway :-/

https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/test/k8s-integration/driver.go#L39

**Comment by verult** [comment]
Ack. I also just remembered kustomize -k uses a very out-of-date version of kustomize, and I checked sometime within the last 3 months I think.
