### ISSUE TITLE
If we don't remove the target path，is there affects？

### ISSUE THREAD

**Issue by zhucan** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#525]
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/317f2a6bf756cfcbc9fa65275ef6e7174e6e9347/pkg/gce-pd-csi-driver/node.go#L232

**Comment by zhucan** [comment]
Because of the openshift sdn container will occupy the dir，the dir status will be busy.

**Comment by msau42** [comment]
My expectation is Unpublish will fail and we will retry until it succeeds.

cc @gnufied and @jsafrane for openshift integration issues

**Comment by msau42** [comment]
I believe in that case then the volume will remain InUse, and if the Pod gets rescheduled to another node, it will be stuck in attach until the 6 minute force detach timeout.

**Comment by zhucan** [comment]
@msau42 yes，if the pod  gets rescheduled to another node，if we umount the target path successfully, why is there mount recording in the sdn container？ I don't know the why sdn container occupy? Could you help me?

**Comment by zhucan** [comment]
In our development csi driver，I can see the target path had been umount successfully，But when we remove the target path, the resource is busy，so the pod will running on other nodes，until the 6 minutes timeout.

target path:
![image](https://user-images.githubusercontent.com/13997135/84456973-0824fb00-ac94-11ea-93d2-4e122b644458.png)
sdn:
![image](https://user-images.githubusercontent.com/13997135/84457052-3f93a780-ac94-11ea-8593-f963d7554a45.png)

mount recording:
![image](https://user-images.githubusercontent.com/13997135/84457078-51754a80-ac94-11ea-84ac-e4dab673b483.png)

**Comment by msau42** [comment]
Thanks for the details! @gnufied @jsafrane can you help out? I'm not familiar with this openshift-sdn container and why it is using this mount.

**Comment by zhucan** [comment]
Because of the sdn container mount all of the path in the node.
![image](https://user-images.githubusercontent.com/13997135/84459800-e1b68e00-ac9a-11ea-9a1d-19af6c8c95a4.png)

**Comment by gnufied** [comment]
Hmm I am aware of similar problem that causes mounts to leak into other namespaces but I have not seen this in awhile with crio. We need to investigate this. Thank you for debugging this one.
