### ISSUE TITLE
change dependency management from dep to go mod

### ISSUE THREAD

**Issue by aayush-rangwala** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#543]
Use the native go toolchain dependency management tool go mod instead of using third party manager dep

**Comment by msau42** [comment]
We do support go mod: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/go.mod

Are you having trouble using go mod?

**Comment by mattcary** [comment]
/close

Please reopen this if go mod isn't working as you expect---AFAIU we've moved off of dep, but quite possibly I've missed something.
