### ISSUE TITLE
ReadWriteMany support

### ISSUE THREAD

**Issue by hadim** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#544]
Is that technically possible to add `ReadWriteMany` support for the CSI GKE driver?

Or is setting up an NFS server the only option to get `ReadWriteMany` ?

**Comment by msau42** [comment]
For a general purpose filesystem, NFS is the easiest way to get `ReadWriteMany`.

To use ReadWriteMany with PD would require using a specialized distributed filesystem or writing your own filesystem layer that could handle the concurrency of multiple writes to the same block device across nodes.

**Comment by hadim** [comment]
Ok, so it's technically possible as-is. Thank you @msau42

**Comment by msau42** [comment]
CSI support for it is not possible yet. It's being worked on in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/415. 

And it's going to be limited in use for only Raw Block mode because of the need to write/provide your own distributed filesystem layer.
