### ISSUE TITLE
Tests are reported twice in testgrid

### ISSUE THREAD

**Issue by mattcary** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#605]
https://testgrid.k8s.io/provider-gcp-compute-persistent-disk-csi-driver#presubmit-gcp-compute-persistent-disk-csi-driver-kubernetes-integration&include-filter-by-regex=volumes%20should%20store%20data

They are only run once as best as I can tell. I guess the testgrid reporting looks in subdirectories for yaml files? This is probably due to my multiple storage class PR.

/assign mattcary

**Comment by msau42** [comment]
Does that mean we don't need to actually merge the junit files?

**Comment by mattcary** [comment]
The merging removes duplicate skipped test entries so it should clean up the output.

I'm also not 100% sure that's the issue---my PR working under that assumption is being tested now, we'll see if it fixes it....

If subdirectories are scanned then maybe it would be better to have duplicate skipped entries and tear out the filter-junit code.

**Comment by mattcary** [comment]
ah, I just realized the presubmit won't show what the testgrid actually looks like. I guess it might be easiest to submit and see what it does?
