### ISSUE TITLE
Add pod wait function in  k8s integration test,  for pd driver start and also prepull image daemonset 

### ISSUE THREAD

**Issue by jingxu97** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#614]
See comments here https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/613#discussion_r493998132

Currently workflow, it waits for certain of of time for prepull calls driver or pr pd csi driver part.

**Comment by mattcary** [comment]
/assign 

I have a PR ready that's waiting on the ADC one (https://github.com/mattcary/gcp-compute-persistent-disk-csi-driver/tree/wait)

It conflicts with the ADC change so it was complicated to send it out for review.

**Comment by mattcary** [comment]
/open

@jingxu97 do we need to do something for the "prepull image daemonset"? We wait on the daemonset deployment, I'm not sure what you mean buy "prepull"

**Comment by jingxu97** [comment]
@mattcary prepull script is starting a daemonSet with specific container image. The purpose is to download image by running those containers. We want to do this before running tests so that all the images are already local when tests start to run. Otherwise, it will definitely exceed 5 mins timeout for pods to start which is coded in the tests.

Yes, we should use your wait script to wait for those daemonSet and then delete them

**Comment by jingxu97** [comment]
somehow it cannot be reopened?

**Comment by mattcary** [comment]
There we go :-)

I just sent a PR for the daemonset issue
