### ISSUE TITLE
Allow use of regional PD in zonal cluster

### ISSUE THREAD

**Issue by mattcary** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#626]
Currently the driver must find 2 zones in order to create a regional PD, making it impossible to use with a zonal cluster.

Customers want to use regional PDs with a zonal cluster, or other cases where the cluster has a single zone, for either multicluster use cases or when there is backup/replication happening outside of k8s.

I believe this could currently be done with a manually provisioned PV, but there have been requests to do this with dynamic provisioning.

I think in order to do this we'll have to add additional parameters to the storage class and maybe additional validation via the metadata server to make sure the selection is consistent with the cluster.

**Comment by msau42** [comment]
This wouldn't work well with WaitForFirstConsumer binding mode, which looks at currently available topology in the cluster

**Comment by msau42** [comment]
I believe if you set AllowedTopology in the storageclass, we don't validate that the topologies actually exist. Need to confirm behavior though.

**Comment by mattcary** [comment]
We do as far as I could tell (when I was testing the regional storage
class).

I could have messed it up, though, and in any case the UX isn't great doing
it that way and could be improved.

However this does just seem to be a problem of plumbing the zones through
in a good way, there's no technical blocker.
