### ISSUE TITLE
setup-project.sh should skip keys creation step for noauth overlay

### ISSUE THREAD

**Issue by saikat-royc** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#639]
In https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/setup-project.sh,
gcloud iam service-accounts keys create step should be skipped when using a noauth overlay.

**Comment by mattcary** [comment]
We already have a CREATE_SA variable to control the project setup.

I was under the impression that this script would only be run once, and rarely, and might be used across multiple deployment overlays. eg it's not run by the test harness like the deploy script is.

I don't know if we can plumb the noauth overlay selection through to here anyway. 

Definitely the documentation around this can be improved.

**Comment by saikat-royc** [comment]
@mattcary  I was thinking more for a first time setup on GCE cluster, where we would like to use the noauth style ADC. The current script, will detect there is no existing SA, and set CREATE_SA=true, and proceed with SA creation and key creation(we could take a new flag SKIP_SA_GENERATION which is false by default). Thoughts?

**Comment by mattcary** [comment]
Yeah, that makes sense. I think we should make the noauth method the default one and nudge everyone towards a streamlined setup. So maybe have SA_KEY_CREATE = false by default

**Comment by mattcary** [comment]
/lifecycle frozen

We should add the SKIP_SA_GENERATION as you suggest.

We can do this in the upcoming fixit.
