### ISSUE TITLE
Support VolumeContentSource.VolumeSource for CreateVolume calls

### ISSUE THREAD

**Issue by saikat-royc** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#663]
PD supports creation of disks from source disks.
https://cloud.google.com/sdk/gcloud/reference/compute/disks/create#--source-disk

PD CSI driver should support this capability

CSI spec for CreateVolume request: https://github.com/container-storage-interface/spec/blob/master/csi.proto#L332

**Comment by msau42** [comment]
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/161

**Comment by halradaideh** [comment]
any updates here ?

**Comment by mattcary** [comment]
/lifecycle frozen

This is in our queue but no specific date yet. (PRs welcome :-)

**Comment by mattcary** [comment]
dup of #161, which is now closed
