### ISSUE TITLE
How to update from an earlier version?

### ISSUE THREAD

**Issue by rgarcia89** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#681]
Hi devs,
I can only find information about how to install or delete the driver.

I remember that last time, that I updated I deleted the old deployment before installing the new one.
Is this still the way to go? If so, should I do this using the delete-driver.sh or what is the preferred method?

It would be nice, if this process could be added to the documentation.
thanks

**Comment by rgarcia89** [comment]
Any update on that?

**Comment by mattcary** [comment]
Hi @rgarcia89, sorry for missing this issue.

Using delete-driver and then redeploying should work. It may also work to just rerun deploy-driver which should update everything appropriately, but that would have to be tested. So delete-driver may be safer even if it's overkill.

Have you tested either method? We'd be interested in hearing in problems you ran into.

Thx

**Comment by rgarcia89** [comment]
hi @mattcary thanks for the update.
I have not tested it so far as I wasn't sure if running delete-driver could not be causing issues.
However, if this is the way to go, I will try my luck.

Maybe still nice to add this to the official documentation ;)
Thanks

**Comment by mattcary** [comment]
Thanks!

Yes, I'll keep this issue open so we can update the docs.

**Comment by rgarcia89** [comment]
@mattcary reminder 😉

**Comment by mattcary** [comment]
Fair play :-)

/lifecycle frozen
/assign @mattcary
