### ISSUE TITLE
Verify udevadm works as intended in driver

### ISSUE THREAD

**Issue by davidz627** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#69]
There exists some manual udevadm triggering in the mount manager code due to a preexisting issue of devices not showing up properly. We need to verify that this udevadm trigger behavior is still called and works properly in this driver

**Comment by msau42** [comment]
This also needs to be ported: https://github.com/kubernetes/kubernetes/pull/66832

**Comment by davidz627** [comment]
Porting the fix is in this issue: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/106
