### ISSUE TITLE
Improve cloud provider layering

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#70]
It may be cleaner to encapsulate the WaitForOp in the cloud provider CreateDisk method, instead of having the driver do it.  This is more in line with how the in-tree driver is implemented.

**Comment by msau42** [comment]
As a side note, could you just use the in-tree cloud provider code?

**Comment by davidz627** [comment]
I thought we wanted to deprecate the in-tree cloud provider code?

**Comment by msau42** [comment]
It's going to be moved out of tree eventually, but the code/interfaces should be the same?
