### ISSUE TITLE
Give more descriptive filenames for sample deployment

### ISSUE THREAD

**Issue by msau42** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#72]
These are really generic names:
    $ export SA_FILE=~/.../cloud-sa.json
    $ export GCEPD_SA_NAME=sample-service-account

It may be better go prefix them with "gce-pd-csi" or something like that.

Also as a side note, because the SA_FILE filename must be cloud-sa.json, it may be better to make the directory configurable, rather than the filename configurable.

**Comment by davidz627** [comment]
solved by #81
