### ISSUE TITLE
integration tests failing sporadically with kustomize problem

### ISSUE THREAD

**Issue by mattcary** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#743]
Kustomize version 3.9.4, which is hardcoded into deploy/kubernetes/install_kustomize.sh, seems to have dropped off of their downloads. We should upgrade to 3.10.0 or 4.0 if possible.

This is causing e2e tests to fail, sporadically for some reason.

/assign

**Comment by msau42** [comment]
Removing released versions is also not good... We should talk with kustomize folks about that

**Comment by mattcary** [comment]
I'm thinking we should just move over to kubectl apply -k. One less dependency.

I know in the past that there's been problems with changes in kustomize versions breaking us, but hopefully that will be less common now that it's baked into kubectl?

**Comment by mattcary** [comment]
Mmm, not only does kubectl not support edit (we use kustomize edit set image), but the kubectl kustomize version is apparently set back in version 2.x.

On the other hand, kustomize has an install-kustomize.sh script that just reaches directly to grab a version without seeing if it's listed in the index. So we can just do that, I tested that it still has our 3.9.4 version.

**Comment by mattcary** [comment]
More background: turns out the issue is not with kustomize, it's that github has a limit of how much is listed in the releases/ index. Kustomize just happens to have a lot of architectures and releases that causes things to fall out of the index pretty quickly. But if you already know the version tag it's still accessible directly.
