### ISSUE TITLE
Error 403: Required 'compute.snapshots.useReadOnly' permission

### ISSUE THREAD

**Issue by lich1710** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#794]
Hi, I am having this issues and thus appreciate your help:

**Background:**

- I did not manually install the driver but enable via GKE console instead, so I assumed all the required roles/iam permission are there?
- I tried to create the PVC from a VolumeSnapshot (which status is already turn to Ready=true)
- Other empty PVC still works fine.

**Error:**

```
Warning  ProvisioningFailed    7m9s (x6 over 24m)    pd.csi.storage.gke.io_gke-6cac98f973e8406185cf-4e90-61a6-vm_77bb06a0-9164-452e-87e1-e0e4738148db  failed to provision volume with StorageClass "ebs-sc": rpc error: code = Internal desc = CreateVolume failed to create single zonal disk "pvc-2644d818-0d00-4f3d-9222-3f93f4fc8e1b": failed to insert zonal disk: unknown Insert disk error: googleapi: Error 403: Required 'compute.snapshots.useReadOnly' permission for 'projects/my-project/global/snapshots/bsc-dataseed-0429-2', forbidden
```

What I have tried:
- Added 'compute.snapshots.useReadOnly` to the service-account that the node is using.

**Comment by lich1710** [comment]
Thanks Mattcary,

I managed to find the SA and assign the permission to it. But the error still happens (Tried recreate the PVC as well).

My permission and roles assignment as below:

```
bindings:
- members:
  - serviceAccount:service-844932802860@container-engine-robot.iam.gserviceaccount.com
  role: projects/tko-bsc/roles/tkoGKESaCustomRole


 ~ gcloud iam roles describe tkoGKESaCustomRole --project=tko-bsc
description: Custom roles to assign to GKE Service Account
etag: BwXFjPLkoCA=
includedPermissions:
- compute.snapshots.useReadOnly
name: projects/tko-bsc/roles/tkoGKESaCustomRole
stage: GA
title: tkoGKESaCustomRole
```

**Comment by mattcary** [comment]
Ah, I see in your first message the error talks about permissions for
'projects/my-project/global/snapshots/....' Maybe you need to replace
my-project with tko-bsc?
