### ISSUE TITLE
Permission problem using gcp-pd-csi: Required 'compute.disks.get' 

### ISSUE THREAD

**Issue by ehmm** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#85]
Hello,
Trying to deploy gcp-pd-csi to a GKE cluster. The deployment works, but trying to attach a disk I get the following error from the attacher:
 
`GRPC error: rpc error: code = Unknown desc = googleapi: Error 403: Required 'compute.disks.get' permission for 'projects/XPROJECT/zones/europe-west3-a/disks/YDISK`

(This is directly from the attacher log but the same error propagates up to the create pod error.

I'm using a service account in the deploy which is set-up as: `Kubernetes Engine Admin, Service Account User, Storage Admin`.

I'm trying to debug if the problem is in the deployment or is the service account missing certain rights.

**Comment by msau42** [comment]
Hi @ehmm, how did you create the service account?

**Comment by ehmm** [comment]
I'm trying to use an existing service account that exists in the project that the GKE cluster is in. Must I create a new one for every cluster?

**Comment by msau42** [comment]
No, you shouldn't need to create a new service account for every cluster.  Can you check that your service account has these roles:
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/setup-project.sh#L22
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/gcp-compute-persistent-disk-csi-driver-custom-role.yaml

**Comment by ehmm** [comment]
Thanks @msau42 it seems that somehow my service account lost the custom-role, adding it back manually fixed the setup.

The issue was with my setup, but I think that maybe it would be a good idea to add a check in the deploy-driver that checks that the service account has the necessary privileges, also passing an argument to the setup-project.sh script that can accept an existing service account and only making sure it has the correct roles.

I will try and create a branch with the above, but this issue can be closed now.

**Comment by ehmm** [comment]
Hi, I've added a better setup-project that checks for existing accounts and only binds role, and also adds a check to the deploy script that the sa used has all the needed roles,
currently it includes a bit of duplication as the needed roles are in both files -- this can be put in an external file but I wasn't sure if it warranted it and how "clean" this would be, can do that to.

Also extracting the project/sa-name from the SA json definitely includes some bash-fu -- not my best moment, if you want I can convert this script to python or something but I wasn't sure if that was needed now. 

Anyway the changes are at: https://github.com/ehmm/gcp-compute-persistent-disk-csi-driver/tree/feature/setupProjectExistingSa

**Comment by davidz627** [comment]
@ehmm took at look at your changes, really appreciate the work you've done on this! Could you please create a Pull Request for your changes so that we can review it and merge to master after

**Comment by davidz627** [comment]
solved by: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/87
