### ISSUE TITLE
Disk delete should specify zone

### ISSUE THREAD

**Issue by mattcary** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#891]
See https://github.com/kubernetes/kubernetes/pull/106819. Does this need to be migrated here or have we already done it?

**Comment by amacaskill** [comment]
I think this is already done. We know what volume to delete by using the volumeID of the DeleteVolumeRequest. If calling [common.VolumeIDToKey(volumeID)](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/pkg/gce-pd-csi-driver/controller.go#L304) doesn't find valid zones, then we return an error.

**Comment by leiyiz** [comment]
Yup looks like VolumeID will always include topology information.
https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/f997312c906d1d3fdce7c98c83e65fb2069909bc/pkg/common/utils.go#L88
