### ISSUE TITLE
Allow configuring metadata via environment variables.

### ISSUE THREAD

**Issue by davidsbond** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#915]
Hello, I am trying to deploy this CSI driver within a [HashiCorp Nomad](https://www.nomadproject.io/) cluster that is _not_ running within GCP, so that I can use GCE disks as persistent storage for my workloads.

An issue I'm running into in the latest version is that on startup the application expects to be able to query the VM's metadata API. Naturally this isn't possible outside of GCP, so in the logs I see:

```
F0204 00:32:36.841454       1 main.go:121] Failed to set up metadata service: failed to get current zone: Get "http://169.254.169.254/computeMetadata/v1/instance/zone": dial tcp 169.254.169.254:80: i/o timeout
```

As the [MetadataService](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/558508cf2d0fac74c60d60c9b88bfb7e4ab741e7/pkg/gce-cloud-provider/metadata/metadata.go#L28) is an `interface` it seems like an implementation could be made that allows for the configuration of metadata via environment variables instead of querying the metadata API. This would allow for deployments outside of GCP

I would like to be able to set each metadata value as an environment variable and perhaps switch to the environment variable implementation by a command-line flag or another environment variable along the lines of `METADATA_USE_ENVIRONMENT`.

**Comment by davidsbond** [comment]
I'd be happy to implement this if deemed a good idea

**Comment by mattcary** [comment]
Can you give a bit more details on your setup? I wasn't aware it was possible to use PD outside of GCP. How does that work? Can you show me an example of attaching a PD manually?
