### ISSUE TITLE
Is gcp-pd the thing patching my PVCs on binding to add a `volumeName:` attr?

### ISSUE THREAD

**Issue by snickell** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#918]
Something has been patching my (supposedly immutable) default storage class (none specified, or specifying `standard`) PVCs lately, patching in a `volumeName` attr on GKE as soon as they are bound.

1. I'm not setting a `volumeName:` attr on my PVCs when I render (checked with a helm render), but when I get them after creation, they now have a volumeName attribute.
2. If helm creates one of these immutable objects, on next upgrade, it will find it wants to patch the PVC to remove the errant `volumeName: addedbygcp-pd-maybe` attr. When it goes to patch it with its three-way-reconciliation strategy, it will try to patch out the `volumeName: ""`, but it can't, because the PVC is of course immutable. 
3. In helmv2 --force could be specified to just delete the resource and recreate (which is still going to cause downtime since the mounted pod(s) will have to be stopped!)
4. The problem is, I believe this completely breaks any PVC-defining chart's `helm upgrade` command for helmv3, which no longer will delete immutable PVCs, even when `helm --force` is specified. So you can't even workaround this issue in helmv3!

A helm template defining a PVC from the zero to jupyterlab helm chart (source: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/templates/hub/pvc.yaml), note no `volumeName` is specified (confirmed by hydrated manifests prior to applying):
```
{{- if eq .Values.hub.db.type "sqlite-pvc" -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "jupyterhub.hub-pvc.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
  {{- with .Values.hub.db.pvc.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.hub.db.pvc.selector }}
  selector:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  {{- if typeIs "string" .Values.hub.db.pvc.storageClassName }}
  storageClassName: {{ .Values.hub.db.pvc.storageClassName | quote }}
  {{- end }}
  accessModes:
    {{- .Values.hub.db.pvc.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.hub.db.pvc.storage | quote }}
{{- end }}
```

As soon as the PVC is bound by gcp-pd it looks like this, notice the volumeName is now set on a supposedly immutable field:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: improc
    meta.helm.sh/release-namespace: improc
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/gce-pd
  creationTimestamp: "2022-02-08T07:38:18Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: jupyterhub
    app.kubernetes.io/managed-by: Helm
    chart: jupyterhub-1.1.3-n306.ha6294dda
    component: hub
    heritage: Helm
    release: improc
    skaffold.dev/run-id: 1adb58fb-a69a-4009-ae68-293a4af5a1b5
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:helm.sh/resource-policy: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:component: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:storageClassName: {}
        f:volumeMode: {}
    manager: helm
    operation: Update
    time: "2022-02-08T07:38:18Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:pv.kubernetes.io/bind-completed: {}
          f:pv.kubernetes.io/bound-by-controller: {}
          f:volume.beta.kubernetes.io/storage-provisioner: {}
      f:spec:
        f:volumeName: {}
      f:status:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-02-08T07:38:19Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:skaffold.dev/run-id: {}
    manager: skaffold
    operation: Update
    time: "2022-02-08T07:38:33Z"
  name: hub-db-dir
  namespace: improc
  resourceVersion: "502821928"
  uid: 8cb612c8-0a63-491f-a547-50c22c25224c
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-8cb612c8-0a63-491f-a547-50c22c25224c
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
```

Next time we helm upgrade the chart we will get this error irregardless of `helm upgrade --force` or not (note helm's 3 way state merge makes this patch confusing, read it as a reverse patch, helm is failing to REMOVE the `VolumeName: "pvc-..."` field and replace it with its rendered state which is `volumeName: ""`
```
Error: UPGRADE FAILED: failed to replace object: PersistentVolumeClaim "hub-db-dir" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
  core.PersistentVolumeClaimSpec{
  	AccessModes:      {"ReadWriteOnce"},
  	Selector:         nil,
  	Resources:        {Requests: {s"storage": {i: {...}, s: "1Gi", Format: "BinarySI"}}},
- 	VolumeName:       "",
+ 	VolumeName:       "pvc-8cb612c8-0a63-491f-a547-50c22c25224c",
  	StorageClassName: &"standard",
  	VolumeMode:       &"Filesystem",
  	DataSource:       nil,
  }
```

Now we can't upgrade our chart anymore :-( 

Have I finally tracked down the culprit at least in gcp-pd? This doesn't happen on a local minikube or kind, and of course, its a little hard to trace.

Apologies if I guessed wrong who's adding the `volumeName` to my PVC!

**Comment by mattcary** [comment]
The VolumeName is updated by the PV controller as part of the process to bind a PVC with its PV. For details on this and on exactly what the immutability of the PVC means, see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L2165) and [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller.go#L113).

Note this is not new behavior, it's been the process as long as there has been PVCs so I don't think it's the cause of your problems. Also note this has nothing to do with the csi driver, this is core k/k behavior.

Looking around at issues on the web it seems that you will run into this problem if your chart has an empty volumeName (see [here](https://github.com/helm/helm/issues/6642) and [here](https://github.com/helm/helm/issues/6642#issuecomment-542836520). 

It doesn't look like you're doing that in your template, but I don't understand helm well so maybe I'm missing something.

At any rate, the volumeName changing is long-standing and expected behavior in k8s, so the problem you're having is either in your chart or in helm itself.

/close

**Comment by snickell** [comment]
@mattcary Hi Matt, thanks for the explanation, I appreciate it more than you know! The upstream helm chart indeed is missing a volumeName, its weird that more of the chart's users haven't run into this, given, as you say, this is a long-standing issue with helm3 and PVC's missing volumeNames.  And thank you so much for directing me to those issues on the helm issue tracker, really above and beyond 🙇🏽‍♀️

**Comment by mattcary** [comment]
👍🏾 happy to help
