### ISSUE TITLE
The same question as "Unable to deploy driver to k8s cluster: error listing CSINodes: the server could not find the requested resource"

### ISSUE THREAD

**Issue by IcoveJ** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#925]
I`m a learner of CSI, and I write a very simple one.
I just implement CreateVolume\Delete\Attach\Detach
In CreateVolume， I simulated a volume：

 56     return &csi.CreateVolumeResponse{
 57         Volume: &csi.Volume{
 58             VolumeId:       "csi-test-volume01",
 59             CapacityBytes:  20 * (1 << 30),
 60             VolumeContext:  req.GetParameters(),
 61         },
 62     }, nil

then wo create sc and pvc, but there`s no pv. When I use "kubectl describe pvc ....." to check，it`s " **error generating accessibility requirements: error listing CSINodes: the server could not find the requested resource** "

someone say my kubernetes version is not right, but they are all 1.23.3

I hope I can get your help

**Comment by mattcary** [comment]
The error message comes from here: https://github.com/kubernetes-sigs/external-provisioner/blob/master/pkg/controller/topology.go#L118

Probably the CSINode objects have not been configured correctly. Did you install a CSIDriver resource for your driver?
