### ISSUE TITLE
Add E2E test flags to specify machine type, zone, OS image, architecture

### ISSUE THREAD

**Issue by pwschuurman** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#944]
Currently the E2E tests spin up two GCE VM instances by default. These install:
 * Test Driver
 * PD CSI Driver that accepts CSI calls

In order to test the PD CSI driver on different machine types that may have different configuration, or operating systems that have different dependencies, we should have flags that control:
 * OS Image: Currently this is hard coded
 * Machine Type: Current default is n1-standard-1
 * Architecture: Dependent on machine-type, built binaries need to match the architecture platform that the driver is running on
 * Zone: If machine types are available in specific zones, this may need to be specified

These flags can likely live in the remote package: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/test/remote

In addition to these flags, the built architecture of the Test Driver and the PD CSI Driver should match. These are built for the e2e test here: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/test/remote/archiver.go#L58

**Comment by mattcary** [comment]
Depending on machine availability we may want to do just internal smoke tests as we do on windows rather than run full integration tests.
