### ISSUE TITLE
Enable Workload Identity for container gce-pd-driver

### ISSUE THREAD

**Issue by achetronic** [kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#952]
Hello there,
I have been deploying this driver by hand and I noticed that the ServiceAccount key is a requirement to be on a Kubernetes Secret. I ended to see this after trying to do it using Workload Identity.

In our company we have a Tooling Stack which can adapt to several cloud providers and can construct the annotations for Service Accounts in Kubernetes dynamically on runtime, so out clusters and tools are generic.

I would open a request to implement the logic for the Workload Identity to cover all cases. Is it possible? the driver for EKS is working fine with IRSA

Regards

**Comment by mattcary** [comment]
On GKE, the driver is available a managed offering and it's not necessary to deploy it manually.

**Comment by achetronic** [comment]
> On GKE, the driver is available a managed offering and it's not necessary to deploy it manually.

I know it is, but there are some use cases where you are interested on disabling the automatic deployment on gcp and take the ownership doing GitOps. 

For example, the csi-driver on EKS can be installed as an addon, but they install some csi containers, but some of them missing (the csi-snapshotter, for example). In the other hand, if you install the package on your own, it is deployed as it, with all the containers, so you can deploy the external-snapshotter later.

On GCP, it is true that the deployment is done correctly by the provider, but may be you prefer to have the same approach in both them, taking the ownership, installing the package, for example using FluxCD.

Now it is impossible to take the whole ownership and that is not desirable for some companies out there.

Could you consider to implement the workload identity approach for these cases? 

Thank you
